### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by eld120** [slashrelativepath/relativepath-cycle-5#5]
As a new project we need to specify our requirements or our intended state so that we have a clear shared end goal.

**Comment by eld120** [comment]
I'm suggesting that we add the following to the README:
Ubuntu 22.04 LTS
nginx (version unclear)
git

**Comment by ChrisForti** [comment]
I added the Ubuntu specs to the read me. It is, probably not formatted right, but I figured I would push what I had. Then we can collaborate via github.
